### ISSUE TITLE
Droits : avoir des admins ET des utilisateurs simples

### ISSUE THREAD

**Issue by borisschapira** [ecvdbdx1617/OnMangeQuoiAMidi#102]
## Comportement attendu

Des admins, qui ont tous les droits.
Des utilisateurs, qui peuvent uniquement créer et participer à des commandes.

## Comportement constaté

Aujourd'hui, soit on est anonyme, soit on a tous les droits.

### Implémentation possible

Commencer par revoir le peuplement de la base pour que plusieurs profils d'utilisateurs soient disponibles (par exemple un par personne dans la salle).

Ensuite, gérer les différents niveaux de droits au niveau de l'affichage et des contrôleurs.

**Comment by Bramvanosta** [comment]
Added by 8900b8a
