### ISSUE TITLE
Modifier Faker pour saisir de vraies adresses

### ISSUE THREAD

**Issue by Clem-o2p** [ecvdbdx1617/OnMangeQuoiAMidi#73]
Les adresses de restaurants saisies par Faker doivent correspondre à de vrais restaurants pour que la fonctionnalité de Map soit opérationnelle.

Il faut créer une méthode custom dans Faker pour lui dire de prendre des adresses de restaus dans un dictionnaire d'adresses qu'on lui fournira

**Comment by Bramvanosta** [comment]
Fixed by 293cc2b
