### ISSUE TITLE
Problème sur la cartographie

### ISSUE THREAD

**Issue by borisschapira** [ecvdbdx1617/OnMangeQuoiAMidi#99]
![capture d ecran 2017-06-21 a 10 42 25](https://user-images.githubusercontent.com/284742/27375089-596940ea-566e-11e7-8757-bf5b305dcf15.png)

**Comment by Clem-o2p** [comment]
Bug dû à #103

**Comment by Bramvanosta** [comment]
Fixed by d7b8b1e
